// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: client.proto

package name.abuchen.portfolio.model.proto.v1;

/**
 * Protobuf type {@code name.abuchen.portfolio.PECBData}
 */
public final class PECBData extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:name.abuchen.portfolio.PECBData)
    PECBDataOrBuilder {
private static final long serialVersionUID = 0L;
  // Use PECBData.newBuilder() to construct.
  private PECBData(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private PECBData() {
    series_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new PECBData();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return name.abuchen.portfolio.model.proto.v1.ClientProtos.internal_static_name_abuchen_portfolio_PECBData_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return name.abuchen.portfolio.model.proto.v1.ClientProtos.internal_static_name_abuchen_portfolio_PECBData_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            name.abuchen.portfolio.model.proto.v1.PECBData.class, name.abuchen.portfolio.model.proto.v1.PECBData.Builder.class);
  }

  public static final int LASTMODIFIED_FIELD_NUMBER = 1;
  private long lastModified_ = 0L;
  /**
   * <code>int64 lastModified = 1;</code>
   * @return The lastModified.
   */
  @java.lang.Override
  public long getLastModified() {
    return lastModified_;
  }

  public static final int SERIES_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private java.util.List<name.abuchen.portfolio.model.proto.v1.PExchangeRateTimeSeries> series_;
  /**
   * <code>repeated .name.abuchen.portfolio.PExchangeRateTimeSeries series = 2;</code>
   */
  @java.lang.Override
  public java.util.List<name.abuchen.portfolio.model.proto.v1.PExchangeRateTimeSeries> getSeriesList() {
    return series_;
  }
  /**
   * <code>repeated .name.abuchen.portfolio.PExchangeRateTimeSeries series = 2;</code>
   */
  @java.lang.Override
  public java.util.List<? extends name.abuchen.portfolio.model.proto.v1.PExchangeRateTimeSeriesOrBuilder> 
      getSeriesOrBuilderList() {
    return series_;
  }
  /**
   * <code>repeated .name.abuchen.portfolio.PExchangeRateTimeSeries series = 2;</code>
   */
  @java.lang.Override
  public int getSeriesCount() {
    return series_.size();
  }
  /**
   * <code>repeated .name.abuchen.portfolio.PExchangeRateTimeSeries series = 2;</code>
   */
  @java.lang.Override
  public name.abuchen.portfolio.model.proto.v1.PExchangeRateTimeSeries getSeries(int index) {
    return series_.get(index);
  }
  /**
   * <code>repeated .name.abuchen.portfolio.PExchangeRateTimeSeries series = 2;</code>
   */
  @java.lang.Override
  public name.abuchen.portfolio.model.proto.v1.PExchangeRateTimeSeriesOrBuilder getSeriesOrBuilder(
      int index) {
    return series_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (lastModified_ != 0L) {
      output.writeInt64(1, lastModified_);
    }
    for (int i = 0; i < series_.size(); i++) {
      output.writeMessage(2, series_.get(i));
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (lastModified_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(1, lastModified_);
    }
    for (int i = 0; i < series_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, series_.get(i));
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof name.abuchen.portfolio.model.proto.v1.PECBData)) {
      return super.equals(obj);
    }
    name.abuchen.portfolio.model.proto.v1.PECBData other = (name.abuchen.portfolio.model.proto.v1.PECBData) obj;

    if (getLastModified()
        != other.getLastModified()) return false;
    if (!getSeriesList()
        .equals(other.getSeriesList())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + LASTMODIFIED_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getLastModified());
    if (getSeriesCount() > 0) {
      hash = (37 * hash) + SERIES_FIELD_NUMBER;
      hash = (53 * hash) + getSeriesList().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static name.abuchen.portfolio.model.proto.v1.PECBData parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static name.abuchen.portfolio.model.proto.v1.PECBData parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static name.abuchen.portfolio.model.proto.v1.PECBData parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static name.abuchen.portfolio.model.proto.v1.PECBData parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static name.abuchen.portfolio.model.proto.v1.PECBData parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static name.abuchen.portfolio.model.proto.v1.PECBData parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static name.abuchen.portfolio.model.proto.v1.PECBData parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static name.abuchen.portfolio.model.proto.v1.PECBData parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static name.abuchen.portfolio.model.proto.v1.PECBData parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static name.abuchen.portfolio.model.proto.v1.PECBData parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static name.abuchen.portfolio.model.proto.v1.PECBData parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static name.abuchen.portfolio.model.proto.v1.PECBData parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(name.abuchen.portfolio.model.proto.v1.PECBData prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code name.abuchen.portfolio.PECBData}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:name.abuchen.portfolio.PECBData)
      name.abuchen.portfolio.model.proto.v1.PECBDataOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return name.abuchen.portfolio.model.proto.v1.ClientProtos.internal_static_name_abuchen_portfolio_PECBData_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return name.abuchen.portfolio.model.proto.v1.ClientProtos.internal_static_name_abuchen_portfolio_PECBData_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              name.abuchen.portfolio.model.proto.v1.PECBData.class, name.abuchen.portfolio.model.proto.v1.PECBData.Builder.class);
    }

    // Construct using name.abuchen.portfolio.model.proto.v1.PECBData.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      lastModified_ = 0L;
      if (seriesBuilder_ == null) {
        series_ = java.util.Collections.emptyList();
      } else {
        series_ = null;
        seriesBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000002);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return name.abuchen.portfolio.model.proto.v1.ClientProtos.internal_static_name_abuchen_portfolio_PECBData_descriptor;
    }

    @java.lang.Override
    public name.abuchen.portfolio.model.proto.v1.PECBData getDefaultInstanceForType() {
      return name.abuchen.portfolio.model.proto.v1.PECBData.getDefaultInstance();
    }

    @java.lang.Override
    public name.abuchen.portfolio.model.proto.v1.PECBData build() {
      name.abuchen.portfolio.model.proto.v1.PECBData result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public name.abuchen.portfolio.model.proto.v1.PECBData buildPartial() {
      name.abuchen.portfolio.model.proto.v1.PECBData result = new name.abuchen.portfolio.model.proto.v1.PECBData(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(name.abuchen.portfolio.model.proto.v1.PECBData result) {
      if (seriesBuilder_ == null) {
        if (((bitField0_ & 0x00000002) != 0)) {
          series_ = java.util.Collections.unmodifiableList(series_);
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.series_ = series_;
      } else {
        result.series_ = seriesBuilder_.build();
      }
    }

    private void buildPartial0(name.abuchen.portfolio.model.proto.v1.PECBData result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.lastModified_ = lastModified_;
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof name.abuchen.portfolio.model.proto.v1.PECBData) {
        return mergeFrom((name.abuchen.portfolio.model.proto.v1.PECBData)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(name.abuchen.portfolio.model.proto.v1.PECBData other) {
      if (other == name.abuchen.portfolio.model.proto.v1.PECBData.getDefaultInstance()) return this;
      if (other.getLastModified() != 0L) {
        setLastModified(other.getLastModified());
      }
      if (seriesBuilder_ == null) {
        if (!other.series_.isEmpty()) {
          if (series_.isEmpty()) {
            series_ = other.series_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensureSeriesIsMutable();
            series_.addAll(other.series_);
          }
          onChanged();
        }
      } else {
        if (!other.series_.isEmpty()) {
          if (seriesBuilder_.isEmpty()) {
            seriesBuilder_.dispose();
            seriesBuilder_ = null;
            series_ = other.series_;
            bitField0_ = (bitField0_ & ~0x00000002);
            seriesBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getSeriesFieldBuilder() : null;
          } else {
            seriesBuilder_.addAllMessages(other.series_);
          }
        }
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              lastModified_ = input.readInt64();
              bitField0_ |= 0x00000001;
              break;
            } // case 8
            case 18: {
              name.abuchen.portfolio.model.proto.v1.PExchangeRateTimeSeries m =
                  input.readMessage(
                      name.abuchen.portfolio.model.proto.v1.PExchangeRateTimeSeries.parser(),
                      extensionRegistry);
              if (seriesBuilder_ == null) {
                ensureSeriesIsMutable();
                series_.add(m);
              } else {
                seriesBuilder_.addMessage(m);
              }
              break;
            } // case 18
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private long lastModified_ ;
    /**
     * <code>int64 lastModified = 1;</code>
     * @return The lastModified.
     */
    @java.lang.Override
    public long getLastModified() {
      return lastModified_;
    }
    /**
     * <code>int64 lastModified = 1;</code>
     * @param value The lastModified to set.
     * @return This builder for chaining.
     */
    public Builder setLastModified(long value) {

      lastModified_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>int64 lastModified = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearLastModified() {
      bitField0_ = (bitField0_ & ~0x00000001);
      lastModified_ = 0L;
      onChanged();
      return this;
    }

    private java.util.List<name.abuchen.portfolio.model.proto.v1.PExchangeRateTimeSeries> series_ =
      java.util.Collections.emptyList();
    private void ensureSeriesIsMutable() {
      if (!((bitField0_ & 0x00000002) != 0)) {
        series_ = new java.util.ArrayList<name.abuchen.portfolio.model.proto.v1.PExchangeRateTimeSeries>(series_);
        bitField0_ |= 0x00000002;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        name.abuchen.portfolio.model.proto.v1.PExchangeRateTimeSeries, name.abuchen.portfolio.model.proto.v1.PExchangeRateTimeSeries.Builder, name.abuchen.portfolio.model.proto.v1.PExchangeRateTimeSeriesOrBuilder> seriesBuilder_;

    /**
     * <code>repeated .name.abuchen.portfolio.PExchangeRateTimeSeries series = 2;</code>
     */
    public java.util.List<name.abuchen.portfolio.model.proto.v1.PExchangeRateTimeSeries> getSeriesList() {
      if (seriesBuilder_ == null) {
        return java.util.Collections.unmodifiableList(series_);
      } else {
        return seriesBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .name.abuchen.portfolio.PExchangeRateTimeSeries series = 2;</code>
     */
    public int getSeriesCount() {
      if (seriesBuilder_ == null) {
        return series_.size();
      } else {
        return seriesBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .name.abuchen.portfolio.PExchangeRateTimeSeries series = 2;</code>
     */
    public name.abuchen.portfolio.model.proto.v1.PExchangeRateTimeSeries getSeries(int index) {
      if (seriesBuilder_ == null) {
        return series_.get(index);
      } else {
        return seriesBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .name.abuchen.portfolio.PExchangeRateTimeSeries series = 2;</code>
     */
    public Builder setSeries(
        int index, name.abuchen.portfolio.model.proto.v1.PExchangeRateTimeSeries value) {
      if (seriesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureSeriesIsMutable();
        series_.set(index, value);
        onChanged();
      } else {
        seriesBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .name.abuchen.portfolio.PExchangeRateTimeSeries series = 2;</code>
     */
    public Builder setSeries(
        int index, name.abuchen.portfolio.model.proto.v1.PExchangeRateTimeSeries.Builder builderForValue) {
      if (seriesBuilder_ == null) {
        ensureSeriesIsMutable();
        series_.set(index, builderForValue.build());
        onChanged();
      } else {
        seriesBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .name.abuchen.portfolio.PExchangeRateTimeSeries series = 2;</code>
     */
    public Builder addSeries(name.abuchen.portfolio.model.proto.v1.PExchangeRateTimeSeries value) {
      if (seriesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureSeriesIsMutable();
        series_.add(value);
        onChanged();
      } else {
        seriesBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .name.abuchen.portfolio.PExchangeRateTimeSeries series = 2;</code>
     */
    public Builder addSeries(
        int index, name.abuchen.portfolio.model.proto.v1.PExchangeRateTimeSeries value) {
      if (seriesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureSeriesIsMutable();
        series_.add(index, value);
        onChanged();
      } else {
        seriesBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .name.abuchen.portfolio.PExchangeRateTimeSeries series = 2;</code>
     */
    public Builder addSeries(
        name.abuchen.portfolio.model.proto.v1.PExchangeRateTimeSeries.Builder builderForValue) {
      if (seriesBuilder_ == null) {
        ensureSeriesIsMutable();
        series_.add(builderForValue.build());
        onChanged();
      } else {
        seriesBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .name.abuchen.portfolio.PExchangeRateTimeSeries series = 2;</code>
     */
    public Builder addSeries(
        int index, name.abuchen.portfolio.model.proto.v1.PExchangeRateTimeSeries.Builder builderForValue) {
      if (seriesBuilder_ == null) {
        ensureSeriesIsMutable();
        series_.add(index, builderForValue.build());
        onChanged();
      } else {
        seriesBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .name.abuchen.portfolio.PExchangeRateTimeSeries series = 2;</code>
     */
    public Builder addAllSeries(
        java.lang.Iterable<? extends name.abuchen.portfolio.model.proto.v1.PExchangeRateTimeSeries> values) {
      if (seriesBuilder_ == null) {
        ensureSeriesIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, series_);
        onChanged();
      } else {
        seriesBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .name.abuchen.portfolio.PExchangeRateTimeSeries series = 2;</code>
     */
    public Builder clearSeries() {
      if (seriesBuilder_ == null) {
        series_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
      } else {
        seriesBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .name.abuchen.portfolio.PExchangeRateTimeSeries series = 2;</code>
     */
    public Builder removeSeries(int index) {
      if (seriesBuilder_ == null) {
        ensureSeriesIsMutable();
        series_.remove(index);
        onChanged();
      } else {
        seriesBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .name.abuchen.portfolio.PExchangeRateTimeSeries series = 2;</code>
     */
    public name.abuchen.portfolio.model.proto.v1.PExchangeRateTimeSeries.Builder getSeriesBuilder(
        int index) {
      return getSeriesFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .name.abuchen.portfolio.PExchangeRateTimeSeries series = 2;</code>
     */
    public name.abuchen.portfolio.model.proto.v1.PExchangeRateTimeSeriesOrBuilder getSeriesOrBuilder(
        int index) {
      if (seriesBuilder_ == null) {
        return series_.get(index);  } else {
        return seriesBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .name.abuchen.portfolio.PExchangeRateTimeSeries series = 2;</code>
     */
    public java.util.List<? extends name.abuchen.portfolio.model.proto.v1.PExchangeRateTimeSeriesOrBuilder> 
         getSeriesOrBuilderList() {
      if (seriesBuilder_ != null) {
        return seriesBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(series_);
      }
    }
    /**
     * <code>repeated .name.abuchen.portfolio.PExchangeRateTimeSeries series = 2;</code>
     */
    public name.abuchen.portfolio.model.proto.v1.PExchangeRateTimeSeries.Builder addSeriesBuilder() {
      return getSeriesFieldBuilder().addBuilder(
          name.abuchen.portfolio.model.proto.v1.PExchangeRateTimeSeries.getDefaultInstance());
    }
    /**
     * <code>repeated .name.abuchen.portfolio.PExchangeRateTimeSeries series = 2;</code>
     */
    public name.abuchen.portfolio.model.proto.v1.PExchangeRateTimeSeries.Builder addSeriesBuilder(
        int index) {
      return getSeriesFieldBuilder().addBuilder(
          index, name.abuchen.portfolio.model.proto.v1.PExchangeRateTimeSeries.getDefaultInstance());
    }
    /**
     * <code>repeated .name.abuchen.portfolio.PExchangeRateTimeSeries series = 2;</code>
     */
    public java.util.List<name.abuchen.portfolio.model.proto.v1.PExchangeRateTimeSeries.Builder> 
         getSeriesBuilderList() {
      return getSeriesFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        name.abuchen.portfolio.model.proto.v1.PExchangeRateTimeSeries, name.abuchen.portfolio.model.proto.v1.PExchangeRateTimeSeries.Builder, name.abuchen.portfolio.model.proto.v1.PExchangeRateTimeSeriesOrBuilder> 
        getSeriesFieldBuilder() {
      if (seriesBuilder_ == null) {
        seriesBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            name.abuchen.portfolio.model.proto.v1.PExchangeRateTimeSeries, name.abuchen.portfolio.model.proto.v1.PExchangeRateTimeSeries.Builder, name.abuchen.portfolio.model.proto.v1.PExchangeRateTimeSeriesOrBuilder>(
                series_,
                ((bitField0_ & 0x00000002) != 0),
                getParentForChildren(),
                isClean());
        series_ = null;
      }
      return seriesBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:name.abuchen.portfolio.PECBData)
  }

  // @@protoc_insertion_point(class_scope:name.abuchen.portfolio.PECBData)
  private static final name.abuchen.portfolio.model.proto.v1.PECBData DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new name.abuchen.portfolio.model.proto.v1.PECBData();
  }

  public static name.abuchen.portfolio.model.proto.v1.PECBData getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<PECBData>
      PARSER = new com.google.protobuf.AbstractParser<PECBData>() {
    @java.lang.Override
    public PECBData parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<PECBData> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<PECBData> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public name.abuchen.portfolio.model.proto.v1.PECBData getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

