// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: client.proto

package name.abuchen.portfolio.model.proto.v1;

public interface PFullHistoricalPriceOrBuilder extends
    // @@protoc_insertion_point(interface_extends:name.abuchen.portfolio.PFullHistoricalPrice)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * epoch day, based on the epoch 1970-01-01
   * </pre>
   *
   * <code>int64 date = 1;</code>
   * @return The date.
   */
  long getDate();

  /**
   * <code>int64 close = 2;</code>
   * @return The close.
   */
  long getClose();

  /**
   * <code>int64 high = 3;</code>
   * @return The high.
   */
  long getHigh();

  /**
   * <code>int64 low = 4;</code>
   * @return The low.
   */
  long getLow();

  /**
   * <code>int64 volume = 5;</code>
   * @return The volume.
   */
  long getVolume();
}
