// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: client.proto

package name.abuchen.portfolio.model.proto.v1;

public interface PFundTransferLotOrBuilder extends
    // @@protoc_insertion_point(interface_extends:name.abuchen.portfolio.PFundTransferLot)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * epoch day, based on the epoch 1970-01-01
   * </pre>
   *
   * <code>int64 acquisitionDate = 1;</code>
   * @return The acquisitionDate.
   */
  long getAcquisitionDate();

  /**
   * <code>int64 sourceShares = 2;</code>
   * @return The sourceShares.
   */
  long getSourceShares();

  /**
   * <code>int64 targetShares = 3;</code>
   * @return The targetShares.
   */
  long getTargetShares();

  /**
   * <code>int64 acquisitionAmount = 4;</code>
   * @return The acquisitionAmount.
   */
  long getAcquisitionAmount();

  /**
   * <code>string acquisitionCurrencyCode = 5;</code>
   * @return The acquisitionCurrencyCode.
   */
  java.lang.String getAcquisitionCurrencyCode();
  /**
   * <code>string acquisitionCurrencyCode = 5;</code>
   * @return The bytes for acquisitionCurrencyCode.
   */
  com.google.protobuf.ByteString
      getAcquisitionCurrencyCodeBytes();

  /**
   * <code>optional string sourceTransaction = 6;</code>
   * @return Whether the sourceTransaction field is set.
   */
  boolean hasSourceTransaction();
  /**
   * <code>optional string sourceTransaction = 6;</code>
   * @return The sourceTransaction.
   */
  java.lang.String getSourceTransaction();
  /**
   * <code>optional string sourceTransaction = 6;</code>
   * @return The bytes for sourceTransaction.
   */
  com.google.protobuf.ByteString
      getSourceTransactionBytes();
}
