// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: name/abuchen/portfolio/model/client.proto

package name.abuchen.portfolio.model.proto.v1;

public interface PLedgerEntryOrBuilder extends
    // @@protoc_insertion_point(interface_extends:name.abuchen.portfolio.PLedgerEntry)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string uuid = 1 [deprecated = true];</code>
   * @deprecated name.abuchen.portfolio.PLedgerEntry.uuid is deprecated.
   *     See name/abuchen/portfolio/model/client.proto;l=245
   * @return The uuid.
   */
  @java.lang.Deprecated java.lang.String getUuid();
  /**
   * <code>string uuid = 1 [deprecated = true];</code>
   * @deprecated name.abuchen.portfolio.PLedgerEntry.uuid is deprecated.
   *     See name/abuchen/portfolio/model/client.proto;l=245
   * @return The bytes for uuid.
   */
  @java.lang.Deprecated com.google.protobuf.ByteString
      getUuidBytes();

  /**
   * <code>.google.protobuf.Timestamp dateTime = 3;</code>
   * @return Whether the dateTime field is set.
   */
  boolean hasDateTime();
  /**
   * <code>.google.protobuf.Timestamp dateTime = 3;</code>
   * @return The dateTime.
   */
  com.google.protobuf.Timestamp getDateTime();
  /**
   * <code>.google.protobuf.Timestamp dateTime = 3;</code>
   */
  com.google.protobuf.TimestampOrBuilder getDateTimeOrBuilder();

  /**
   * <code>optional string note = 4;</code>
   * @return Whether the note field is set.
   */
  boolean hasNote();
  /**
   * <code>optional string note = 4;</code>
   * @return The note.
   */
  java.lang.String getNote();
  /**
   * <code>optional string note = 4;</code>
   * @return The bytes for note.
   */
  com.google.protobuf.ByteString
      getNoteBytes();

  /**
   * <code>optional string source = 5;</code>
   * @return Whether the source field is set.
   */
  boolean hasSource();
  /**
   * <code>optional string source = 5;</code>
   * @return The source.
   */
  java.lang.String getSource();
  /**
   * <code>optional string source = 5;</code>
   * @return The bytes for source.
   */
  com.google.protobuf.ByteString
      getSourceBytes();

  /**
   * <code>.google.protobuf.Timestamp updatedAt = 6;</code>
   * @return Whether the updatedAt field is set.
   */
  boolean hasUpdatedAt();
  /**
   * <code>.google.protobuf.Timestamp updatedAt = 6;</code>
   * @return The updatedAt.
   */
  com.google.protobuf.Timestamp getUpdatedAt();
  /**
   * <code>.google.protobuf.Timestamp updatedAt = 6;</code>
   */
  com.google.protobuf.TimestampOrBuilder getUpdatedAtOrBuilder();

  /**
   * <code>repeated .name.abuchen.portfolio.PLedgerPosting postings = 7;</code>
   */
  java.util.List<name.abuchen.portfolio.model.proto.v1.PLedgerPosting>
      getPostingsList();
  /**
   * <code>repeated .name.abuchen.portfolio.PLedgerPosting postings = 7;</code>
   */
  name.abuchen.portfolio.model.proto.v1.PLedgerPosting getPostings(int index);
  /**
   * <code>repeated .name.abuchen.portfolio.PLedgerPosting postings = 7;</code>
   */
  int getPostingsCount();
  /**
   * <code>repeated .name.abuchen.portfolio.PLedgerPosting postings = 7;</code>
   */
  java.util.List<? extends name.abuchen.portfolio.model.proto.v1.PLedgerPostingOrBuilder>
      getPostingsOrBuilderList();
  /**
   * <code>repeated .name.abuchen.portfolio.PLedgerPosting postings = 7;</code>
   */
  name.abuchen.portfolio.model.proto.v1.PLedgerPostingOrBuilder getPostingsOrBuilder(
      int index);

  /**
   * <code>optional string typeCode = 9;</code>
   * @return Whether the typeCode field is set.
   */
  boolean hasTypeCode();
  /**
   * <code>optional string typeCode = 9;</code>
   * @return The typeCode.
   */
  java.lang.String getTypeCode();
  /**
   * <code>optional string typeCode = 9;</code>
   * @return The bytes for typeCode.
   */
  com.google.protobuf.ByteString
      getTypeCodeBytes();

  /**
   * <code>repeated .name.abuchen.portfolio.PLedgerParameter parameters = 10;</code>
   */
  java.util.List<name.abuchen.portfolio.model.proto.v1.PLedgerParameter>
      getParametersList();
  /**
   * <code>repeated .name.abuchen.portfolio.PLedgerParameter parameters = 10;</code>
   */
  name.abuchen.portfolio.model.proto.v1.PLedgerParameter getParameters(int index);
  /**
   * <code>repeated .name.abuchen.portfolio.PLedgerParameter parameters = 10;</code>
   */
  int getParametersCount();
  /**
   * <code>repeated .name.abuchen.portfolio.PLedgerParameter parameters = 10;</code>
   */
  java.util.List<? extends name.abuchen.portfolio.model.proto.v1.PLedgerParameterOrBuilder>
      getParametersOrBuilderList();
  /**
   * <code>repeated .name.abuchen.portfolio.PLedgerParameter parameters = 10;</code>
   */
  name.abuchen.portfolio.model.proto.v1.PLedgerParameterOrBuilder getParametersOrBuilder(
      int index);
}
