// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: client.proto

package name.abuchen.portfolio.model.proto.v1;

public interface PLedgerPostingOrBuilder extends
    // @@protoc_insertion_point(interface_extends:name.abuchen.portfolio.PLedgerPosting)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string uuid = 1;</code>
   * @return The uuid.
   */
  java.lang.String getUuid();
  /**
   * <code>string uuid = 1;</code>
   * @return The bytes for uuid.
   */
  com.google.protobuf.ByteString
      getUuidBytes();

  /**
   * <code>int64 amount = 3;</code>
   * @return The amount.
   */
  long getAmount();

  /**
   * <code>optional string currency = 4;</code>
   * @return Whether the currency field is set.
   */
  boolean hasCurrency();
  /**
   * <code>optional string currency = 4;</code>
   * @return The currency.
   */
  java.lang.String getCurrency();
  /**
   * <code>optional string currency = 4;</code>
   * @return The bytes for currency.
   */
  com.google.protobuf.ByteString
      getCurrencyBytes();

  /**
   * <code>optional int64 forexAmount = 5;</code>
   * @return Whether the forexAmount field is set.
   */
  boolean hasForexAmount();
  /**
   * <code>optional int64 forexAmount = 5;</code>
   * @return The forexAmount.
   */
  long getForexAmount();

  /**
   * <code>optional string forexCurrency = 6;</code>
   * @return Whether the forexCurrency field is set.
   */
  boolean hasForexCurrency();
  /**
   * <code>optional string forexCurrency = 6;</code>
   * @return The forexCurrency.
   */
  java.lang.String getForexCurrency();
  /**
   * <code>optional string forexCurrency = 6;</code>
   * @return The bytes for forexCurrency.
   */
  com.google.protobuf.ByteString
      getForexCurrencyBytes();

  /**
   * <code>optional .name.abuchen.portfolio.PDecimalValue exchangeRate = 7;</code>
   * @return Whether the exchangeRate field is set.
   */
  boolean hasExchangeRate();
  /**
   * <code>optional .name.abuchen.portfolio.PDecimalValue exchangeRate = 7;</code>
   * @return The exchangeRate.
   */
  name.abuchen.portfolio.model.proto.v1.PDecimalValue getExchangeRate();
  /**
   * <code>optional .name.abuchen.portfolio.PDecimalValue exchangeRate = 7;</code>
   */
  name.abuchen.portfolio.model.proto.v1.PDecimalValueOrBuilder getExchangeRateOrBuilder();

  /**
   * <code>optional string security = 8;</code>
   * @return Whether the security field is set.
   */
  boolean hasSecurity();
  /**
   * <code>optional string security = 8;</code>
   * @return The security.
   */
  java.lang.String getSecurity();
  /**
   * <code>optional string security = 8;</code>
   * @return The bytes for security.
   */
  com.google.protobuf.ByteString
      getSecurityBytes();

  /**
   * <code>int64 shares = 9;</code>
   * @return The shares.
   */
  long getShares();

  /**
   * <code>optional string account = 10;</code>
   * @return Whether the account field is set.
   */
  boolean hasAccount();
  /**
   * <code>optional string account = 10;</code>
   * @return The account.
   */
  java.lang.String getAccount();
  /**
   * <code>optional string account = 10;</code>
   * @return The bytes for account.
   */
  com.google.protobuf.ByteString
      getAccountBytes();

  /**
   * <code>optional string portfolio = 11;</code>
   * @return Whether the portfolio field is set.
   */
  boolean hasPortfolio();
  /**
   * <code>optional string portfolio = 11;</code>
   * @return The portfolio.
   */
  java.lang.String getPortfolio();
  /**
   * <code>optional string portfolio = 11;</code>
   * @return The bytes for portfolio.
   */
  com.google.protobuf.ByteString
      getPortfolioBytes();

  /**
   * <code>repeated .name.abuchen.portfolio.PLedgerParameter parameters = 12;</code>
   */
  java.util.List<name.abuchen.portfolio.model.proto.v1.PLedgerParameter>
      getParametersList();
  /**
   * <code>repeated .name.abuchen.portfolio.PLedgerParameter parameters = 12;</code>
   */
  name.abuchen.portfolio.model.proto.v1.PLedgerParameter getParameters(int index);
  /**
   * <code>repeated .name.abuchen.portfolio.PLedgerParameter parameters = 12;</code>
   */
  int getParametersCount();
  /**
   * <code>repeated .name.abuchen.portfolio.PLedgerParameter parameters = 12;</code>
   */
  java.util.List<? extends name.abuchen.portfolio.model.proto.v1.PLedgerParameterOrBuilder>
      getParametersOrBuilderList();
  /**
   * <code>repeated .name.abuchen.portfolio.PLedgerParameter parameters = 12;</code>
   */
  name.abuchen.portfolio.model.proto.v1.PLedgerParameterOrBuilder getParametersOrBuilder(
      int index);

  /**
   * <code>optional string typeCode = 13;</code>
   * @return Whether the typeCode field is set.
   */
  boolean hasTypeCode();
  /**
   * <code>optional string typeCode = 13;</code>
   * @return The typeCode.
   */
  java.lang.String getTypeCode();
  /**
   * <code>optional string typeCode = 13;</code>
   * @return The bytes for typeCode.
   */
  com.google.protobuf.ByteString
      getTypeCodeBytes();
}
