// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: client.proto

package name.abuchen.portfolio.model.proto.v1;

public interface PLedgerOrBuilder extends
    // @@protoc_insertion_point(interface_extends:name.abuchen.portfolio.PLedger)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .name.abuchen.portfolio.PLedgerEntry entries = 1;</code>
   */
  java.util.List<name.abuchen.portfolio.model.proto.v1.PLedgerEntry> 
      getEntriesList();
  /**
   * <code>repeated .name.abuchen.portfolio.PLedgerEntry entries = 1;</code>
   */
  name.abuchen.portfolio.model.proto.v1.PLedgerEntry getEntries(int index);
  /**
   * <code>repeated .name.abuchen.portfolio.PLedgerEntry entries = 1;</code>
   */
  int getEntriesCount();
  /**
   * <code>repeated .name.abuchen.portfolio.PLedgerEntry entries = 1;</code>
   */
  java.util.List<? extends name.abuchen.portfolio.model.proto.v1.PLedgerEntryOrBuilder> 
      getEntriesOrBuilderList();
  /**
   * <code>repeated .name.abuchen.portfolio.PLedgerEntry entries = 1;</code>
   */
  name.abuchen.portfolio.model.proto.v1.PLedgerEntryOrBuilder getEntriesOrBuilder(
      int index);
}
