// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: client.proto

package name.abuchen.portfolio.model.proto.v1;

public interface PLedgerProjectionMembershipOrBuilder extends
    // @@protoc_insertion_point(interface_extends:name.abuchen.portfolio.PLedgerProjectionMembership)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string postingUUID = 1;</code>
   * @return The postingUUID.
   */
  java.lang.String getPostingUUID();
  /**
   * <code>string postingUUID = 1;</code>
   * @return The bytes for postingUUID.
   */
  com.google.protobuf.ByteString
      getPostingUUIDBytes();

  /**
   * <code>.name.abuchen.portfolio.PLedgerProjectionMembershipRole role = 2;</code>
   * @return The enum numeric value on the wire for role.
   */
  int getRoleValue();
  /**
   * <code>.name.abuchen.portfolio.PLedgerProjectionMembershipRole role = 2;</code>
   * @return The role.
   */
  name.abuchen.portfolio.model.proto.v1.PLedgerProjectionMembershipRole getRole();
}
