// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: client.proto

package name.abuchen.portfolio.model.proto.v1;

public interface PLedgerEntryOrBuilder extends
    // @@protoc_insertion_point(interface_extends:name.abuchen.portfolio.PLedgerEntry)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string uuid = 1;</code>
   * @return The uuid.
   */
  java.lang.String getUuid();
  /**
   * <code>string uuid = 1;</code>
   * @return The bytes for uuid.
   */
  com.google.protobuf.ByteString
      getUuidBytes();

  /**
   * <code>.google.protobuf.Timestamp dateTime = 3;</code>
   * @return Whether the dateTime field is set.
   */
  boolean hasDateTime();
  /**
   * <code>.google.protobuf.Timestamp dateTime = 3;</code>
   * @return The dateTime.
   */
  com.google.protobuf.Timestamp getDateTime();
  /**
   * <code>.google.protobuf.Timestamp dateTime = 3;</code>
   */
  com.google.protobuf.TimestampOrBuilder getDateTimeOrBuilder();

  /**
   * <code>optional string note = 4;</code>
   * @return Whether the note field is set.
   */
  boolean hasNote();
  /**
   * <code>optional string note = 4;</code>
   * @return The note.
   */
  java.lang.String getNote();
  /**
   * <code>optional string note = 4;</code>
   * @return The bytes for note.
   */
  com.google.protobuf.ByteString
      getNoteBytes();

  /**
   * <code>optional string source = 5;</code>
   * @return Whether the source field is set.
   */
  boolean hasSource();
  /**
   * <code>optional string source = 5;</code>
   * @return The source.
   */
  java.lang.String getSource();
  /**
   * <code>optional string source = 5;</code>
   * @return The bytes for source.
   */
  com.google.protobuf.ByteString
      getSourceBytes();

  /**
   * <code>.google.protobuf.Timestamp updatedAt = 6;</code>
   * @return Whether the updatedAt field is set.
   */
  boolean hasUpdatedAt();
  /**
   * <code>.google.protobuf.Timestamp updatedAt = 6;</code>
   * @return The updatedAt.
   */
  com.google.protobuf.Timestamp getUpdatedAt();
  /**
   * <code>.google.protobuf.Timestamp updatedAt = 6;</code>
   */
  com.google.protobuf.TimestampOrBuilder getUpdatedAtOrBuilder();

  /**
   * <code>repeated .name.abuchen.portfolio.PLedgerPosting postings = 7;</code>
   */
  java.util.List<name.abuchen.portfolio.model.proto.v1.PLedgerPosting>
      getPostingsList();
  /**
   * <code>repeated .name.abuchen.portfolio.PLedgerPosting postings = 7;</code>
   */
  name.abuchen.portfolio.model.proto.v1.PLedgerPosting getPostings(int index);
  /**
   * <code>repeated .name.abuchen.portfolio.PLedgerPosting postings = 7;</code>
   */
  int getPostingsCount();
  /**
   * <code>repeated .name.abuchen.portfolio.PLedgerPosting postings = 7;</code>
   */
  java.util.List<? extends name.abuchen.portfolio.model.proto.v1.PLedgerPostingOrBuilder>
      getPostingsOrBuilderList();
  /**
   * <code>repeated .name.abuchen.portfolio.PLedgerPosting postings = 7;</code>
   */
  name.abuchen.portfolio.model.proto.v1.PLedgerPostingOrBuilder getPostingsOrBuilder(
      int index);

  /**
   * <code>repeated .name.abuchen.portfolio.PLedgerProjectionRef projectionRefs = 8;</code>
   */
  java.util.List<name.abuchen.portfolio.model.proto.v1.PLedgerProjectionRef>
      getProjectionRefsList();
  /**
   * <code>repeated .name.abuchen.portfolio.PLedgerProjectionRef projectionRefs = 8;</code>
   */
  name.abuchen.portfolio.model.proto.v1.PLedgerProjectionRef getProjectionRefs(int index);
  /**
   * <code>repeated .name.abuchen.portfolio.PLedgerProjectionRef projectionRefs = 8;</code>
   */
  int getProjectionRefsCount();
  /**
   * <code>repeated .name.abuchen.portfolio.PLedgerProjectionRef projectionRefs = 8;</code>
   */
  java.util.List<? extends name.abuchen.portfolio.model.proto.v1.PLedgerProjectionRefOrBuilder>
      getProjectionRefsOrBuilderList();
  /**
   * <code>repeated .name.abuchen.portfolio.PLedgerProjectionRef projectionRefs = 8;</code>
   */
  name.abuchen.portfolio.model.proto.v1.PLedgerProjectionRefOrBuilder getProjectionRefsOrBuilder(
      int index);

  /**
   * <code>optional uint32 typeId = 9;</code>
   * @return Whether the typeId field is set.
   */
  boolean hasTypeId();
  /**
   * <code>optional uint32 typeId = 9;</code>
   * @return The typeId.
   */
  int getTypeId();

  /**
   * <code>repeated .name.abuchen.portfolio.PLedgerParameter parameters = 10;</code>
   */
  java.util.List<name.abuchen.portfolio.model.proto.v1.PLedgerParameter>
      getParametersList();
  /**
   * <code>repeated .name.abuchen.portfolio.PLedgerParameter parameters = 10;</code>
   */
  name.abuchen.portfolio.model.proto.v1.PLedgerParameter getParameters(int index);
  /**
   * <code>repeated .name.abuchen.portfolio.PLedgerParameter parameters = 10;</code>
   */
  int getParametersCount();
  /**
   * <code>repeated .name.abuchen.portfolio.PLedgerParameter parameters = 10;</code>
   */
  java.util.List<? extends name.abuchen.portfolio.model.proto.v1.PLedgerParameterOrBuilder>
      getParametersOrBuilderList();
  /**
   * <code>repeated .name.abuchen.portfolio.PLedgerParameter parameters = 10;</code>
   */
  name.abuchen.portfolio.model.proto.v1.PLedgerParameterOrBuilder getParametersOrBuilder(
      int index);
}
